# Generated by Django 3.2.16 on 2022-10-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_event',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('DATE', 'Date'), ('BUSINESS', 'Business Dinner'), ('HEN', 'Hen Party'), ('STAG', 'Stag Party'), ('NONE', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
