# Generated by Django 3.2.16 on 2022-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20221025_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_event',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('DATE', 'Date'), ('BUSINESS', 'Business Dinner'), ('HEN', 'Hen Party'), ('STAG', 'Stag Party'), ('NONE', 'None')], max_length=50, verbose_name='Is this a Special Occasion?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(auto_now=True, choices=[('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Number of Guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='title',
            field=models.CharField(blank=True, max_length=4, verbose_name='Title'),
        ),
    ]
