# Generated by Django 3.2.16 on 2022-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20221027_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
