# Generated by Django 3.2.16 on 2022-11-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='user',
        ),
    ]
